### ISSUE TITLE
[StackSpot AI] Criação de APIs de Knowledge Source API

### ISSUE THREAD

**Issue by fernandosantoszup** [zup-archive/stackspot-studio-data-roadmap#133]
**Descrição**

**DOD**

Tasks:

API

- [x] APIs públicas da Stackspot 
- [x] API Google Maps

**Comment by elpasckezup** [comment]
Não é possível cadastrar API do google. 

StackSpot não permite upload acima de 500Kb.
![Image](https://github.com/stack-spot/stackspot-studio-content-roadmap/assets/105730076/9b431c5d-0ace-41d7-b1ca-732d41eede79)

OpenAPI do Google Maps é de 2,3Mb
![Image](https://github.com/stack-spot/stackspot-studio-content-roadmap/assets/105730076/85f1d71c-67ee-4017-8874-1db0000b7f8d)

**Comment by elpasckezup** [comment]
Google Maps API cadastrado. Formato precisa estar em json.
