### ISSUE TITLE
[InnerSource] H0 - Template de Contribuição PR

### ISSUE THREAD

**Issue by luizcarloszup** [zup-archive/stackspot-studio-data-roadmap#179]
TODO
- [x] Criar e testar template de contribuição para PR
- [x] Aplicar template no repo TemplateRepository
- [x] Criar repositório de teste e validar template

**Comment by danielmaion** [comment]
Validado com sucesso no repositório:
https://github.com/StackSpot-Labs/stk-plugin-app-java-quarkus-test
