### ISSUE TITLE
[InnerSource] H1 - Workflow de validação do Documentação Conteúdo

### ISSUE THREAD

**Issue by luizcarloszup** [zup-archive/stackspot-studio-data-roadmap#180]
TODO
- [x] Criar e testar action para validação de README.md
- [x] Criar e configurar repositório de reusable workflow
- [x] Aplicar action no repo de TemplateRepository
- [x] Criar repositório de teste com action
- [x] Replicar workflow para todos os repositórios existentes

**Comment by danielmaion** [comment]
Repositório de reusable workflows criado:
https://github.com/StackSpot-Labs/reusable-workflows

Implementação do reusable workflow no repositório de templates:
https://github.com/StackSpot-Labs/TemplateRepository/blob/danielmaionzup-patch-1/.github/workflows/markdown-check.yml

**Comment by danielmaion** [comment]
Validado com sucesso no repositório:
https://github.com/StackSpot-Labs/stk-plugin-app-java-quarkus-test
