### ISSUE TITLE
[DM] Producer: H1 - Implementar alterar versão Terraform

### ISSUE THREAD

**Issue by luizcarloszup** [zup-archive/stackspot-studio-data-roadmap#189]
Efetuar atualizações do Producer Toolkit.

- [x]  Alterar Versão Terraform
- [x]  Alterar MarkDown Documentação Terraform
DOD: Ter melhorias no Producer Toolkit homologadas e publicada na Branch MAIN do Producer toolkit

**Comment by danielmaion** [comment]
PR: https://github.com/stack-spot/supporting-content-dm-plugin-producer/pull/22
