### ISSUE TITLE
[DM] Adapter Dynamo: H1 - Implementar alteração versão Terraform

### ISSUE THREAD

**Issue by luizcarloszup** [zup-archive/stackspot-studio-data-roadmap#191]
Efetuar atualizações do Adapter DynamoDb .

- [ ]  Alterar Versão Terraform
- [ ]  Alterar MarkDown Documentação Terraform
DOD: Ter melhorias no Adapter DynamoDb homologadas e publicada na Branch MAIN do Adapter DynamoDb

**Comment by danielmaion** [comment]
PR: https://github.com/stack-spot/supporting-content-dm-plugin-ingestion-dynamo/pull/11
